### ISSUE TITLE
Test with modified whitespace is not compiling.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire#3]
Source code:
```
fn
double
(n :Int)->Int{
            return(n*2);
}

io.putchar(double(21)+37);
```

Result:
```
 $ python sapphire main.sph main.b
error: invalid syntax (<sapphire>, line 1)
```

Detailed error messages are nice.

**Comment by maviek** [comment]
![image](https://user-images.githubusercontent.com/29343327/53568310-e288e680-3b61-11e9-8802-4113df322e3c.png)

**Comment by KrzysztofSzewczyk** [comment]
![obraz](https://user-images.githubusercontent.com/27734421/53568432-46131400-3b62-11e9-9640-a3e448cace78.png)

**Comment by maviek** [comment]
Update python to 3.6
