### ISSUE TITLE
Fourth test is crashing

### ISSUE THREAD

**Issue by maviek** [SapphireProject/sapphire#6]
Sometimes this **fourth test is crashing**. On average, **once every seven** attempts.
```python
def f(n):
    if n - 2 == 1:
        return n
    else:
        return n*2

print(48+f(3))
print(48+f(4))
```
**Expected output** is `38`

**Comment by KrzysztofSzewczyk** [comment]
It's technically impossible, maybe it's result of system misconfiguration?
Unless user interaction changes, all applications are expected to work in same manner everytime.
It's fundamental concept of universal Turing machine so implicitly this applies to asm2bf making it a comprehensible assembler.
Doesn't the code attempt to execute the procedure using `in_`?

**Comment by maviek** [comment]
Okay, I do not want to do this. I'm too lazy
